### ISSUE TITLE
Crash on Worldgen when a furnace is placed and filled by worldgen

### ISSUE THREAD

**Issue by Derpford** [focamacho/HotFurnace#1]
When a worldgen feature tries to place an item inside a furnace, it causes a crash on load:
[latest.log](https://github.com/TelepathicGrunt/Blame/files/6805972/latest.log)

**Comment by focamacho** [comment]
It appears that when the item is being inserted, the world is still "null" for the furnace.
I think it was fixed in the latest version of the mod, thanks for the report.
